### ISSUE TITLE
meeting[team](09-23-2024): Standup

### ISSUE THREAD

**Issue by aarnphm** [aarnphm/tinymorph#58]
## date and time.

09-23-2024

## attendance.

- [x] [Aaron](@aarnphm)
- [x] [Lucas](@Hoshino-Kiichi)
- [x] [Nebras](@nebrask)
- [x] [Waleed](@waleedmalik7)

## agenda.

- Discussion on team name
- Decision on POC, whether to build editors or web-based.

## TODO.

- [ ] @aarnphm to send smiths emails how to submit documentations hosted through GitHub pages
- [ ] finalize POC and development plan for specific components
- [ ] setup meeting for design thinking wrt to workflow and UI interaction

## references

- [Obsidian Flavor Markdown](https://help.obsidian.md/Editing+and+formatting/Obsidian+Flavored+Markdown)
- [GitHub Flavor Markdown](https://github.github.com/gfm/)
- [Nextra for monorepo on frontend](https://github.com/shuding/nextra)
